# Generated by Django 2.0.6 on 2018-10-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='myurl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个人主站地址'),
        ),
    ]
