# Generated by Django 2.0.6 on 2018-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181025_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_url',
            field=models.ImageField(null=True, upload_to='', verbose_name='博客图示'),
        ),
        migrations.AddField(
            model_name='blog',
            name='page_url',
            field=models.URLField(null=True, verbose_name='博文主页'),
        ),
    ]
