# Generated by Django 2.0.6 on 2018-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181030_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='page_url',
            field=models.URLField(blank=True, null=True, verbose_name='博文主页'),
        ),
    ]
