# Generated by Django 2.0.6 on 2018-11-01 03:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181101_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
